
DROP TABLE CONTACTS;
CREATE TABLE CONTACTS (
   MEMBER_ID VARCHAR(20) NOT NULL PRIMARY KEY,  
   CHNAME VARCHAR(20),    
   ENGNAME VARCHAR(20) NOT NULL,  
   ID VARCHAR(20),      -- Changed to VARCHAR(20)
   BIRTHDAY DATE,         
   PHONE VARCHAR(20),
   IBMER VARCHAR(1),
   COMPETITION VARCHAR(2)
);  

DROP TABLE attendances;
CREATE TABLE attendances (
   MEMBER_ID VARCHAR(20) NOT NULL,
   PRACTICE_DATE DATE NOT NULL,
   CONSTRAINT FK_attendances FOREIGN KEY (MEMBER_ID) REFERENCES CONTACTS(MEMBER_ID),
   PRIMARY KEY (MEMBER_ID, PRACTICE_DATE)
);

DROP TABLE memberfee;
CREATE TABLE memberfee (
   MEMBER_ID VARCHAR(20) NOT NULL,
   PAID_DATE DATE NOT NULL,
   CONSTRAINT FK_memberfee FOREIGN KEY (MEMBER_ID) REFERENCES CONTACTS(MEMBER_ID),
   PRIMARY KEY (MEMBER_ID, PAID_DATE)
);

DROP TABLE item;
CREATE TABLE item (
   EXPENSE_NAME VARCHAR(50) NOT NULL,
   AMOUNT INTEGER NOT NULL,
   MEMBER VARCHAR(20) NOT NULL,
   PRIMARY KEY (EXPENSE_NAME, AMOUNT,MEMBER)
);


DROP TABLE EXPENSES;
CREATE TABLE EXPENSES (
    CHNAME VARCHAR(50), 
    MEMBER_ID VARCHAR(20),
    EXPENSE_NAME VARCHAR(50), 
    QTY INTEGER,
    UPDATE_DATE DATE,
    CONSTRAINT FK_EXPENSES FOREIGN KEY (MEMBER_ID) REFERENCES CONTACTS(MEMBER_ID)
);

DROP TABLE PAYMENT;
CREATE TABLE PAYMENT ( 
   MEMBER_ID VARCHAR(20),
   DESCRIPTION VARCHAR(30),
   PAID_AMOUNT INTEGER, 
   PAYMENT_DATE DATE,
   CONSTRAINT FK_PAYMENT FOREIGN KEY (MEMBER_ID) REFERENCES CONTACTS(MEMBER_ID)
);

DROP TABLE TIMEOFF;
CREATE TABLE TIMEOFF(
    ENGNAME VARCHAR(20) NOT NULL,
    TIMEOFF_DATE DATE,
    REASON VARCHAR(2)
)
